    spring.application.name=ecommerce-api-springboot

    # Database Configuration
    spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
    spring.datasource.username=ecommerce_user
    spring.datasource.password=root
    spring.datasource.driver-class-name=org.postgresql.Driver

    # JPA/Hibernate Configuration
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    spring.jpa.properties.hibernate.format_sql=true
    spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

    # Server Configuration
    server.port=8080

    # Thymeleaf Configuration
    spring.thymeleaf.cache=false

    # Logging
    logging.level.com.harsh.ecommerce=DEBUG

    # JWT Configuration
    app.jwt.secret=6JceBQIEQZXpiooARpn5iTVw6eifLBp_UKGuDdrZMkg=
    app.jwt.expiration=3600000

    cloudinary.cloud-name=CLOUDINARY_CLOUD_NAME
    cloudinary.api-key=CLOUDINARY_API_KEY
    cloudinary.api-secret=CLOUDINARY_API_SECRET